### ISSUE TITLE
Bug: rename `__dirName` to `__dirname`

### ISSUE THREAD

**Issue by eeriksp** [ozum/vuepress-bar#18]
First of all, thank you for this package! The ability to focus on writing to content rather than configuring is a great benefit.

I tried to use the sample from README:

```js
const getConfig = require("vuepress-bar");

module.exports = {
  themeConfig: {
    ...getConfig(`${__dirName}/..`)
  }
};
```
This resulted in `ReferenceError: __dirName is not defined`. I think that  `__dirName` should be renamed to `__dirname`.

**Comment by ozum** [comment]
Thanks @eeriksp. You are right it was a typo. I fixed README.
