### ISSUE TITLE
Errors on console

### ISSUE THREAD

**Issue by eeriksp** [ozum/vuepress-bar#19]
I tried the `example-standard` project from the `docs` directory.
It seems to work fine, but I get these errors on the console

Any ideas what might be causing this?

![image](https://user-images.githubusercontent.com/35540617/78310951-1cdc6880-7558-11ea-83c5-2aeb2ceec9d7.png)

**Comment by ozum** [comment]
@eeriksp, I checked and all tests are passing. Could you please verify steps below if it works for you?

1. Create an empty directory.
1. Clone this repo.
1. `npm install`
1. `npm test`

**Comment by eeriksp** [comment]
The problem was that my index file was named `index.md`, renaming it to `README.md` fixed the issue.

**Comment by ozum** [comment]
I'm happy it is solved.
