### ISSUE TITLE
Wrong directory separator on Windows

### ISSUE THREAD

**Issue by nirebu** [ozum/vuepress-bar#2]
I was trying to use your plugin to autobuild the navbar and sidebar, but I found an issue while using the structure `nav.foldername` to build the navbar.

The plugin would build the `$themeConfig.nav[].link` as `\nav.foldername\`, thus breaking the navigation and sidebar loading.

I nailed down the cause to being on Windows, because the same config, run through a Linux VM works no problem, generating the parameters right as `/nav.foldername/` both in the `nav` object and `sidebar` groups keys.

Is there a way to hardcode the correct browser separator to be `/` ?

Thank you very much

**Comment by ozum** [comment]
Thanks for the PR.
