### ISSUE TITLE
sidebar display error

### ISSUE THREAD

**Issue by tofulife** [ozum/vuepress-bar#20]
- Nav.01.xx
  - Nav.01.aa
    - aa
    - Bb
  - Nav.02.bb
    - Cc
- Nav.10.yy

**the sidebar is ok**

**but when  I change to** 
- Nav.01.xx
  - Nav.01.aa
    - aa
    - Bb
  - Nav.02.bb
    - Cc
- Nav.10.yy
  - Nav.20.dd
    - Dd

**the sidebar about yy does not display, xx can also display**

**Comment by ozum** [comment]
Hi @tofulife, could you please create a sample git repo showing error. So I can investigate.

**Comment by tofulife** [comment]
> Hi @tofulife, could you please create a sample git repo showing error. So I can investigate.

Of course. the url of sample git repo is `git@github.com:tofulife/vuepressTest.git`
SIdebar "Vue2"  from "Navbar2 copy"does not show except "home", but the "vue"  from "Navbar2"does.
I hope it will not bother you, thank you !

**Comment by ozum** [comment]
Hi @tofulife, I added a fix and published to npm. Could you please try with latest version from npm?

**Comment by tofulife** [comment]
> Hi @tofulife, could you please create a sample git repo showing error. So I can investigate.

Of course. the url of sample git repo is `git@github.com:tofulife/vuepressTest.git`
SIdebar "Vue2"  from "Navbar2 copy"does not show except "home", but the "vue"  from "Navbar2"does.
I hope it will not bother you, thank you !


> Hi @tofulife, I added a fix and published to npm. Could you please try with latest version from npm?

Thank you very much!
