### ISSUE TITLE
pinyinNav:true,only change nav but sidebar

### ISSUE THREAD

**Issue by LbhFront-end** [ozum/vuepress-bar#23]
![image](https://user-images.githubusercontent.com/30042334/92669459-34f4b700-f344-11ea-9afc-4982c04ea533.png)

**Comment by ozum** [comment]
pinyin support is added thanks to @boboidream. @boboidream do you have any suggestion?

**Comment by boboidream** [comment]
Did you use the `permalink-pinyin` plugin  ? it works for me.  @ozum @LbhFront-end

```
# /.vuepress/config.js
plugins: ['permalink-pinyin', ['autobar', {'pinyinNav': true}], 'rpurl'],
```

**Comment by weijie0** [comment]
any update?

**Comment by ozum** [comment]
I need a PR for this.
