### ISSUE TITLE
Hi! Why do the sidebars show home when adding a second and third navigation bar

### ISSUE THREAD

**Issue by Jaredhi** [ozum/vuepress-bar#30]

**Comment by ozum** [comment]
@Jaredhi, could you please create an example repo in English, so I can investigate.

**Comment by Jaredhi** [comment]
@ozum, Sorry, my internet connection to github is a bit slow.
This is my sample repository, https://github.com/Jaredhi/vuepress.git
The problem is that the page that clicks on the second navigation bar link cannot generate the corresponding sidebar

**Comment by ozum** [comment]
@Jaredhi, I checked your sample repository. Yes, it shows a "Home" link, but your repository does not use "vuepress-bar". `vuepress-plugin-autobar` is not developed by me.

I uninstalled `vuepress-plugin-autobar` and installed `vuepress-bar`:

```
$ npm uninstall vuepress-plugin-autobar
$ npm install vuepress-bar
```

Using the config below, it works as expected and does not have a "Home" link.

```js
const getConfig = require("vuepress-bar");

const { nav, sidebar } = getConfig();

module.exports = {
  title: 'blog',
  description: '',
  head: [
    ['link', { rel: 'icon', href: '/img/tx.jpg' }]
  ],
  base: '/',
  themeConfig: { nav, sidebar } ,
  plugins: [
    ['permalink-pinyin'],
    // ['autobar', { 'pinyinNav': true },],
    'rpurl'
  ]
}
```

![image](https://user-images.githubusercontent.com/1497060/111896414-8df78300-8a2a-11eb-8948-af90484d66ef.png)

**Comment by Jaredhi** [comment]
It has been resolved, thank you so much
