### ISSUE TITLE
Sidebar is not defined

### ISSUE THREAD

**Issue by chris-dnv** [ozum/vuepress-bar#31]
I'm trying to add the sidebar filter as per the Readme however on the build i get ReferenceError: sidebar is not defined.  Could you help please?

Themeconfig in config.js

![image](https://user-images.githubusercontent.com/55097248/115747343-76971700-a395-11eb-92d7-c62cc59c9ddf.png)

**Comment by ozum** [comment]
It's a JavaScript error. You didn't define the `sidebar` variable anywhere. First define the variable.

Please see the example below. Actually, it is the same example in README, but I added comments.

```js
// Here we define sidebar variable.
const { nav, sidebar } = getConfig();


module.exports = {
  themeConfig: {
    nav,
	
	// Here we can use the sidebar variable defined above.
    sidebar: sidebar.filter((i) => i.title !== "Node Modules"),
  }
};
```

**Comment by chris-dnv** [comment]
Thank you Ozum this was indeed the initial issue,  

However no matter what title i try to filter i get the following error on build : 

TypeError: Cannot read property 'filter' of undefined

themeConfig:` {
      ...getConfig(`${__dirname}/..`),
      logo: "/logo.png",
      nav: [
        { text: 'Home', link: '/' },
        { text: 'VoA2.0', link: '/01.VoA 2.0 Design/' },
        { text: 'VoA China', link: '/02.VoA China Design/' },
      ],
      sidebar: sidebar.filter((i) => i.title !== "VoA China Design"),
                  },plugins: [


![image](https://user-images.githubusercontent.com/55097248/115882732-57f45700-a44d-11eb-8df6-8b9903b86bfc.png)

**Comment by ozum** [comment]
This problem seems again related to JS. First, try `console.log(sidebar)` or other debugging methods to see what is the content of the `sidebar` variable.
