### ISSUE TITLE
mixDirectoriesAndFilesAlphabetically (and numerically?) does not seem to work

### ISSUE THREAD

**Issue by ssuess** [ozum/vuepress-bar#41]
I thought I had the same issue as [this one](https://github.com/ozum/vuepress-bar/issues/36), but now I believe it is different. Giving a number to both directories and documents in the same folder does not order them as one would expect. Only the documents are ordered, and the directories fall after that. Here is my tree for example:
```
├── 01.getting-started
│   ├── data-sources.md
│   ├── documentation.md
│   └── faq.md
├── 02.data-api
│   ├── 01.data-api.md
│   ├── assets
│   └── contact-finder.md
├── 03.the-ui
│   ├── 01.releases
│   │   ├── 202109241339.md
│   │   └── README.md
│   └── 02.ui-features.md
└── README.md
```
I would expect the folder `01.releases` to show in the list under `03.the-ui` first, before `02.ui-features`, but it does not. If I name a file instead of a folder there, it does properly sort.  So the issue is mixing files and directories with numbering. 

Btw, folders (like the top level above) DO sort correctly relative to each other, just not to documents in the same tree. (Documents always seem to display before directories)

And there seems to be a config setting that sets this by default to true (if I am understanding it correctly) but it does not work setting it to either true or false: mixDirectoriesAndFilesAlphabetically

Thanks btw for this really great plugin!

**Comment by ozum** [comment]
Hi @ssuess, could you please create a sample repo replicating the issue, so I can examine the case?

**Comment by ssuess** [comment]
Sure: https://github.com/ssuess/vpbartest

**Comment by ozum** [comment]
@ssuess, thanks for creating the repo. I have fixed the issue. If it's not fixed, please open a new case.

Best,

**Comment by ssuess** [comment]
Seems to work, thanks!
