### ISSUE TITLE
Diacritics are not preserved in headings

### ISSUE THREAD

**Issue by lttr** [ozum/vuepress-bar#9]
In method `getName` there is call to `startCase` function from lodash. Unfortunately, this function is not preserving diacritics, which does not make sence in this context for a lot of languages.

I propose to change it to use function `capitalize` from lodash, or maybe some fancy regexp which works with unicode like this:

```js
// remove puctuation, extra spaces and for every word apply capitalize function
name.replace(/\p{P}+/ug, ' ').trim().replace(/\p{L}+/ug, capitalize)
```

**Comment by ozum** [comment]
Could you please retest with latest version?

**Comment by lttr** [comment]
I'm sorry, have you changed anything? I don't see new release. Last week I have used the latest version.

**Comment by ozum** [comment]
Ah, sorry I thought it is related to `translitePinyin` in this [PR](https://github.com/ozum/vuepress-bar/pull/6/files).

Does `capitalize` from lodash protect diacritics such as `ü` -> `Ü`.

**Comment by ozum** [comment]
I fixed it, please update to latest version.

**Comment by lttr** [comment]
Thanks, it works as expected.
